import flet as ft


#! FINISH the view desing

def pizza_View(router):
    #* defining view content

    content = ft.Column([
            ft.Text("Size",size=30),
            ft.CupertinoCheckbox(label="Small"),
            ft.CupertinoCheckbox(label="Medium"),
            ft.CupertinoCheckbox(label="Large"),
            ft.Text("Sause",size=30),
            ft.CupertinoCheckbox(label="Classic Red Sauce"),
            ft.CupertinoCheckbox(label="White Sauce"),
            ft.CupertinoCheckbox(label="Pesto Sauce"),
            ft.CupertinoCheckbox(label="BBQ Sauce"),
            ft.Text("Crust",size=30),
            ft.CupertinoCheckbox(label="Thin Crust"),
            ft.CupertinoCheckbox(label="Thick Crust"),
            ft.CupertinoCheckbox(label="Stuffed Crust"),
            ft.CupertinoCheckbox(label="small"),
            ft.Text("Ingredients",size=30),
            ft.CupertinoCheckbox(label="Pepperoni"),  
            ft.CupertinoCheckbox(label="Mushrooms"),  
            ft.CupertinoCheckbox(label="Onions"),  
            ft.CupertinoCheckbox(label="Green Peppers"),  
            ft.CupertinoCheckbox(label="Black Olives"),  
            ft.CupertinoCheckbox(label="Italian Sausage"),  
            ft.CupertinoCheckbox(label="Bacon"),  
            ft.CupertinoCheckbox(label="Ham"),  
            ft.CupertinoCheckbox(label="Pineapple"),  
            ft.CupertinoCheckbox(label="Spinach"),  
            ft.CupertinoCheckbox(label="Garlic"),  
            ft.CupertinoCheckbox(label="Basil"),  
            ft.CupertinoCheckbox(label="Tomato Slices"),  
            ft.CupertinoCheckbox(label="Chicken"),  
            ft.CupertinoCheckbox(label="Jalapeños"),  
            ft.CupertinoCheckbox(label="Anchovies"),  
            ft.CupertinoCheckbox(label="Artichokes"),  
            ft.CupertinoCheckbox(label="Sun-Dried Tomatoes"),  
            ft.CupertinoCheckbox(label="Arugula"),  
            ft.CupertinoCheckbox(label="Red Peppers"),  
            ft.CupertinoCheckbox(label="Broccoli"),  
            ft.CupertinoCheckbox(label="Eggplant"),  
            ft.CupertinoCheckbox(label="Zucchini"),  
            ft.CupertinoCheckbox(label="Prosciutto"),  
            ft.CupertinoCheckbox(label="Salami"),  
            ft.CupertinoCheckbox(label="Crushed Red Pepper"),  
            ft.CupertinoCheckbox(label="Oregano"),  
            ft.CupertinoCheckbox(label="Thyme"),  
            ft.CupertinoCheckbox(label="Truffle Oil"),  
            ft.CupertinoCheckbox(label="Olive Oil"),  
            ft.CupertinoCheckbox(label="Capers"),  
            ft.CupertinoCheckbox(label="Sweet Corn"),  
            ft.CupertinoCheckbox(label="Ground Beef"),  
            ft.CupertinoCheckbox(label="Chorizo"),  
            ft.CupertinoCheckbox(label="Turkey"),  
            ft.CupertinoCheckbox(label="Tofu"),  
            ft.CupertinoCheckbox(label="Caramelized Onions"),  
            ft.CupertinoCheckbox(label="Roasted Garlic"),  
            ft.CupertinoCheckbox(label="Chili Flakes"),  
            ft.CupertinoCheckbox(label="Lemon Zest"),  
            ft.CupertinoCheckbox(label="Sour Cream"),  
    ])
    return content